import Head from 'next/head';
import Footer from '../components/Footer';
import Features from '../components/Features';
import Security from '../components/Security';
import { DemoGif } from '../components/common';
import WhyOthent from '../components/WhyOthent';
import HowItWorks from '../components/HowItWorks';
import HeroSection from '../components/HeroSection';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Othent</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <HeroSection />
        <DemoGif>
          <img src='/demo.svg' alt='demo-gif' />
        </DemoGif>
        <Features />
        <HowItWorks />
        <Security />
        <WhyOthent />
      </main>

      <Footer />
    </div>
  );
}
